services:
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
#Ver o que é possível automatizar na criação de dbs p/ camadas